#!/bin/bash
# Make GraalVM `native-image` available and nothing else
GRAALVM_VERSION=19.0.0
GRAALVM_PARENT_DIRECTORY=${HOME}/.local/share
GRAAL_DIRECTORY=${GRAALVM_PARENT_DIRECTORY}/${GRAALVM_DISTRIBUTION}
case $(uname | tr '[:upper:]' '[:lower:]') in
  linux*)
    export OS_NAME=linux
    ;;
  darwin*)
    export OS_NAME=darwin
    ;;
esac
TAR_GZ_FILENAME=graalvm-ce-${OS_NAME}-amd64-${GRAALVM_VERSION}.tar.gz
TAR_GZ_URL=https://github.com/oracle/graal/releases/download/vm-${GRAALVM_VERSION}/${TAR_GZ_FILENAME}
${GRAAL_DIRECTORY}/Contents/Home/bin/gu install native-image
NATIVE_IMAGE=${GRAAL_DIRECTORY}/Contents/Home/bin/native-image
NATIVE_IMAGE_TARGET_DIRECTORY=${HOME}/.local/bin
NATIVE_IMAGE_TARGET=${NATIVE_IMAGE_TARGET_DIRECTORY}/native-image
if [[ ! -f ${NATIVE_IMAGE} ]]
then
  (mkdir -p ${GRAALVM_PARENT_DIRECTORY} &&
    cd ${GRAALVM_PARENT_DIRECTORY} &&
    wget -O ${TAR_GZ_FILENAME} ${TAR_GZ_URL} &&
    tar zxf ${TAR_GZ_FILENAME} &&
    rm -f ${TAR_GZ_FILENAME})
fi
ls -lsa ${NATIVE_IMAGE}
mkdir -p ${NATIVE_IMAGE_TARGET_DIRECTORY}
ln -f -s ${NATIVE_IMAGE} ${NATIVE_IMAGE_TARGET}
export PATH=${NATIVE_IMAGE_TARGET_DIRECTORY}:${PATH}
